# run conda env create --file environment.yml
name: template-env
channels:
- conda-forge
dependencies:
 - python=3.8.5
 - numpy
 - requests
 - scikit-learn
 - pandas
 - click
 - matplotlib
 # - pytorch
 # - jupyter
 - pip
 - pytest
 - pre_commit
 - black
 - flake8
 - pip:



